language: python
python:
  - "3.5"
services:
  - docker
env:
  - VERSION=1.0
script:
  - docker build -t xianzixiang/go_builder:$VERSION .
  - echo "$DOCKER_USERNAME"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push xianzixiang/go_builder:$VERSION
